# import modules for numpy

In [1]:
import numpy as np

In [82]:
wines=np.genfromtxt(r"C:\Users\1mscdsa19\Downloads\winequality-red.csv",delimiter=';',skip_header=1)
print(wines)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [83]:
wines.shape

(1599, 12)

In [84]:
wines.shape[0]

1599

In [85]:
wines.shape[1]

12

In [86]:
wines.ndim

2

In [87]:
type(wines)

numpy.ndarray

In [88]:
wines.dtype

dtype('float64')

In [89]:
wines[:5]

array([[7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02, 1.100e+01,
        3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00, 5.000e+00],
       [7.800e+00, 8.800e-01, 0.000e+00, 2.600e+00, 9.800e-02, 2.500e+01,
        6.700e+01, 9.968e-01, 3.200e+00, 6.800e-01, 9.800e+00, 5.000e+00],
       [7.800e+00, 7.600e-01, 4.000e-02, 2.300e+00, 9.200e-02, 1.500e+01,
        5.400e+01, 9.970e-01, 3.260e+00, 6.500e-01, 9.800e+00, 5.000e+00],
       [1.120e+01, 2.800e-01, 5.600e-01, 1.900e+00, 7.500e-02, 1.700e+01,
        6.000e+01, 9.980e-01, 3.160e+00, 5.800e-01, 9.800e+00, 6.000e+00],
       [7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02, 1.100e+01,
        3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00, 5.000e+00]])

In [90]:
wines[2][3]

2.3

In [91]:
wines[:3,3]

array([1.9, 2.6, 2.3])

In [92]:
wines[::,0]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

In [93]:
wines[1,::]

array([ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    , 67.    ,
        0.9968,  3.2   ,  0.68  ,  9.8   ,  5.    ])

In [94]:
wines[1:4,4]

array([0.098, 0.092, 0.075])

In [95]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [96]:
#updated
wines[0,0]=100
wines[0,0]

100.0

In [97]:
wines[0,0]=7.4

In [98]:
a=wines[3,:]
a

array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 ,  9.8  ,  6.   ])

In [99]:
a[1]

0.28

In [100]:
wines.astype(int)

array([[ 7,  0,  0, ...,  0,  9,  5],
       [ 7,  0,  0, ...,  0,  9,  5],
       [ 7,  0,  0, ...,  0,  9,  5],
       ...,
       [ 6,  0,  0, ...,  0, 11,  6],
       [ 5,  0,  0, ...,  0, 10,  5],
       [ 6,  0,  0, ...,  0, 11,  6]])

# Vectorization Operations

In [101]:
wines[::,11]

array([5., 5., 5., ..., 6., 5., 6.])

In [108]:
a=wines[::,11]+10
a

array([15., 15., 15., ..., 16., 15., 16.])

In [109]:
wines[::,10]

array([ 9.4,  9.8,  9.8, ..., 11. , 10.2, 11. ])

In [111]:
b=wines[::,10]*3
b

array([28.2, 29.4, 29.4, ..., 33. , 30.6, 33. ])

In [116]:
c=a+a
c

array([30., 30., 30., ..., 32., 30., 32.])

In [118]:
d=a*b
d

array([423., 441., 441., ..., 528., 459., 528.])

# Broadcasting

In [122]:
rand_array=np.random.random((12))

In [123]:
rand_array

array([0.45947749, 0.29530318, 0.14166228, 0.53873357, 0.33612682,
       0.28291428, 0.47085438, 0.50794113, 0.95749896, 0.9773805 ,
       0.81863483, 0.68463816])

In [124]:
wines+rand_array

array([[ 7.85947749,  0.99530318,  0.14166228, ...,  1.5373805 ,
        10.21863483,  5.68463816],
       [ 8.25947749,  1.17530318,  0.14166228, ...,  1.6573805 ,
        10.61863483,  5.68463816],
       [ 8.25947749,  1.05530318,  0.18166228, ...,  1.6273805 ,
        10.61863483,  5.68463816],
       ...,
       [ 6.75947749,  0.80530318,  0.27166228, ...,  1.7273805 ,
        11.81863483,  6.68463816],
       [ 6.35947749,  0.94030318,  0.26166228, ...,  1.6873805 ,
        11.01863483,  5.68463816],
       [ 6.45947749,  0.60530318,  0.61166228, ...,  1.6373805 ,
        11.81863483,  6.68463816]])